name: versions

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  local-version:
    runs-on: macos-latest
    name: Run local action version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add new key/value pairs Info.plist
        uses: ./
        with:
          info-plist-path: './samples/Info.plist'
          key-value-json: '[{"FirstCustomKey": "Some Value to store"}, {"SecondCustomKey": "Another Value"}]'
          print-file: true
      - name: Update existing Key Info2.plist
        uses: ./
        with:
          info-plist-path: './samples/Info2.plist'
          key-value-json: '[{"FirstCustomKey": "Some new Value"}, {"SecondCustomKey": "Another Value"}]'
          print-file: true